### ISSUE TITLE
Initial search not working.

### ISSUE THREAD

**Issue by Vishesh-Pandey** [Vishesh-Pandey/v-music#1]
When you open the website and search for music for the first time it won't work.

**Comment by RajShukla1** [comment]
Its working perfectly on my browser

**Comment by ashish-khankari** [comment]
Could You assign me this task, I would love to contribute and please describe in detail about issue

**Comment by sika-007** [comment]
Hello Vishesh. I've spent quite a while looking into this problem and I don't think there is anything wrong with the client-side code. The error seems to be coming from the server which the API request has been made to.

**Comment by Vishesh-Pandey** [comment]
Even I think the same. Let me close this issue then.
