### ISSUE TITLE
Search on enter

### ISSUE THREAD

**Issue by Gradient-Lover** [Vishesh-Pandey/v-music#3]
**Not able to search just by pressing the Enter key.**

**Comment by Sky-De** [comment]
Hi there
Assign this to me
I will fix it as soon as i get assignment

**Comment by Sky-De** [comment]
i've got a question to ask
did you mean you wnat search just only on pressing Enter key ?

**Comment by Gallantfarhan** [comment]
hey, if nobody is working on this issue, I can fix the issue assign me this issue.

**Comment by Vishesh-Pandey** [comment]
We are closing this issue. We have very limited API calls and hence going to close the development of this website as of now.
